/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle.remoto;

import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author Eduar
 */
public class Controle extends javax.swing.JFrame {
    
    Timer temporizador;
    String temporizador_canal = "";

    /**
     * Creates new form Controle
     */
    public Controle() {
        initComponents();
        
        controleobj = new ControleRemoto();
        Tv.setVisible(false);
        LBnetflix.setVisible (false);
        LBmute.setVisible(false);
        LBlegendas.setVisible (false);
        LBmenu1.setVisible(false);
        
    }
    private ControleRemoto controleobj;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btpower = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        btvolmais = new javax.swing.JButton();
        btvolmenos = new javax.swing.JButton();
        btcanalmais = new javax.swing.JButton();
        btmute = new javax.swing.JButton();
        btmenu = new javax.swing.JButton();
        btnetflix = new javax.swing.JButton();
        btnTrocaCacais = new javax.swing.JButton();
        btzoom = new javax.swing.JButton();
        btcanalmenos = new javax.swing.JButton();
        btcc = new javax.swing.JButton();
        Tv = new javax.swing.JPanel();
        LBnetflix = new javax.swing.JLabel();
        LBcanal = new javax.swing.JLabel();
        LBzero = new javax.swing.JLabel();
        LBvolume = new javax.swing.JLabel();
        LB0 = new javax.swing.JLabel();
        LBlegendas = new javax.swing.JLabel();
        LBzoom = new javax.swing.JLabel();
        LBmute = new javax.swing.JLabel();
        LBmenu1 = new javax.swing.JPanel();
        LBconfig = new javax.swing.JLabel();
        LBaudio = new javax.swing.JLabel();
        LBnet = new javax.swing.JLabel();
        LBmenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btpower.setText("POWER");
        btpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpowerActionPerformed(evt);
            }
        });

        bt1.setText("1");
        bt1.setEnabled(false);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("2");
        bt2.setEnabled(false);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setText("3");
        bt3.setEnabled(false);

        bt4.setText("4");
        bt4.setEnabled(false);

        bt5.setText("5");
        bt5.setEnabled(false);

        bt6.setText("6");
        bt6.setEnabled(false);

        bt7.setText("7");
        bt7.setEnabled(false);

        bt8.setText("8");
        bt8.setEnabled(false);

        bt9.setText("9");
        bt9.setEnabled(false);

        bt10.setText("0");
        bt10.setEnabled(false);

        btvolmais.setText("Vol +");
        btvolmais.setEnabled(false);

        btvolmenos.setText("Vol -");
        btvolmenos.setEnabled(false);

        btcanalmais.setText("CH +");
        btcanalmais.setEnabled(false);

        btmute.setText("Mute");
        btmute.setDefaultCapable(false);
        btmute.setEnabled(false);
        btmute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmuteActionPerformed(evt);
            }
        });

        btmenu.setText("Menu");
        btmenu.setEnabled(false);
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });

        btnetflix.setText("Netflix");
        btnetflix.setEnabled(false);
        btnetflix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnetflixActionPerformed(evt);
            }
        });

        btnTrocaCacais.setText("Troca Canal");
        btnTrocaCacais.setEnabled(false);
        btnTrocaCacais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaCanal(evt);
            }
        });

        btzoom.setText("Zoom In");
        btzoom.setEnabled(false);
        btzoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btzoomActionPerformed(evt);
            }
        });

        btcanalmenos.setText("CH -");
        btcanalmenos.setEnabled(false);

        btcc.setText("CC");
        btcc.setEnabled(false);
        btcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btccActionPerformed(evt);
            }
        });

        Tv.setBackground(new java.awt.Color(0, 0, 0));

        LBnetflix.setForeground(new java.awt.Color(255, 0, 0));
        LBnetflix.setText("NETFLIX ");

        LBcanal.setText("CANAL:");

        LBzero.setText("0");

        LBvolume.setText("VOLUME:");

        LB0.setText("0");

        LBlegendas.setBackground(new java.awt.Color(0, 255, 255));
        LBlegendas.setForeground(new java.awt.Color(204, 204, 0));
        LBlegendas.setText("Legendas Ligadas ");

        LBzoom.setForeground(new java.awt.Color(0, 255, 0));
        LBzoom.setText("Zoom ");

        LBmute.setText("Mudo");

        LBconfig.setText("Configurações");

        LBaudio.setText("Audio ");

        LBnet.setText("Internet ");

        LBmenu.setText("Menu ");

        javax.swing.GroupLayout LBmenu1Layout = new javax.swing.GroupLayout(LBmenu1);
        LBmenu1.setLayout(LBmenu1Layout);
        LBmenu1Layout.setHorizontalGroup(
            LBmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LBmenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LBmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LBmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LBconfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBnet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBaudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LBmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        LBmenu1Layout.setVerticalGroup(
            LBmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LBmenu1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LBmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBaudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBnet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout TvLayout = new javax.swing.GroupLayout(Tv);
        Tv.setLayout(TvLayout);
        TvLayout.setHorizontalGroup(
            TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TvLayout.createSequentialGroup()
                .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TvLayout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(LBmute))
                    .addGroup(TvLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBnetflix, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TvLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TvLayout.createSequentialGroup()
                                        .addComponent(LBcanal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(LBzero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(TvLayout.createSequentialGroup()
                                        .addComponent(LBvolume)
                                        .addGap(41, 41, 41)
                                        .addComponent(LB0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(TvLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LBlegendas))
                    .addGroup(TvLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LBzoom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(427, 427, 427)))
                .addGap(34, 34, 34))
            .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TvLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        TvLayout.setVerticalGroup(
            TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TvLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LBmute)
                .addGap(34, 34, 34)
                .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBcanal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TvLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(LBzero)))
                .addGap(38, 38, 38)
                .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBvolume)
                    .addComponent(LB0))
                .addGap(24, 24, 24)
                .addComponent(LBnetflix, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(LBlegendas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(LBzoom)
                .addGap(29, 29, 29)
                .addComponent(LBmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(TvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TvLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btpower))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt1)
                        .addGap(18, 18, 18)
                        .addComponent(bt2)
                        .addGap(17, 17, 17)
                        .addComponent(bt3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt4)
                        .addGap(18, 18, 18)
                        .addComponent(bt5)
                        .addGap(18, 18, 18)
                        .addComponent(bt6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt7)
                        .addGap(18, 18, 18)
                        .addComponent(bt8)
                        .addGap(17, 17, 17)
                        .addComponent(bt9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmute, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(bt10)
                        .addGap(12, 12, 12)
                        .addComponent(btcc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btvolmais)
                        .addGap(45, 45, 45)
                        .addComponent(btcanalmais))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btmenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btvolmenos)
                        .addGap(49, 49, 49)
                        .addComponent(btcanalmenos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnetflix, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btzoom)))
                    .addGap(3, 3, 3)
                    .addComponent(btnTrocaCanal(btnTrocaCanal))
                .addGap(31, 31, 31)
                .addComponent(Tv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btpower)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt1)
                            .addComponent(bt2)
                            .addComponent(bt3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt4)
                            .addComponent(bt5)
                            .addComponent(bt6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt7)
                            .addComponent(bt8)
                            .addComponent(bt9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btmute)
                            .addComponent(bt10)
                            .addComponent(btcc))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btvolmais)
                            .addComponent(btcanalmais))
                        .addGap(11, 11, 11)
                        .addComponent(btmenu)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btvolmenos)
                            .addComponent(btcanalmenos))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnetflix)
                            .addComponent(btzoom)))
                            .addComponent(btnTrocaCanal)
                    .addComponent(Tv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpowerActionPerformed
        controleobj.power();
        atualiza();
    }//GEN-LAST:event_btpowerActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void btmuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmuteActionPerformed
        controleobj.mute();
        atualiza();
    }//GEN-LAST:event_btmuteActionPerformed

    private void btnetflixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnetflixActionPerformed
        controleobj.netflix();
        atualiza ();
    }//GEN-LAST:event_btnetflixActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
        controleobj.menu();
        atualiza ();
    }//GEN-LAST:event_btmenuActionPerformed

    private void btccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btccActionPerformed
        controleobj.captions();
        atualiza ();
    }//GEN-LAST:event_btccActionPerformed

    private void btnTrocaCanal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btccActionPerformed
        controleobj.trocadecanais(1);
        atualiza ();
    }//GEN-LAST:event_btccActionPerformed

    private void btzoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btzoomActionPerformed
        controleobj.zoom();
        atualiza ();
    }//GEN-LAST:event_btzoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controle().setVisible(true);
            }
        });
    }
          
        public void atualiza (){
            if (controleobj.power == 1){
                Tv.setVisible (true);
                bt1.setEnabled(true );
                bt2.setEnabled(true );
                bt3.setEnabled(true );
                bt4.setEnabled(true );
                bt5.setEnabled(true );
                bt6.setEnabled(true );
                bt6.setEnabled(true );
                bt7.setEnabled(true );
                bt8.setEnabled(true );
                bt9.setEnabled(true );
                bt10.setEnabled(true );
                btnetflix.setEnabled(true );
                btvolmais.setEnabled(true );
                btvolmenos.setEnabled(true );
                btcanalmais.setEnabled(true );
                btcanalmenos.setEnabled(true );
                btzoom.setEnabled(true );
                btmenu.setEnabled(true );
                btmute.setEnabled(true );
                btcc.setEnabled(true );   
               
            } else {
                Tv.setVisible(false);
                bt1.setEnabled(false);
                bt2.setEnabled(false);
                bt3.setEnabled(false);
                bt4.setEnabled(false);
                bt5.setEnabled(false);
                bt6.setEnabled(false);
                bt6.setEnabled(false);
                bt7.setEnabled(false);
                bt8.setEnabled(false);
                bt9.setEnabled(false);
                bt10.setEnabled(false);
                btnetflix.setEnabled(false);
                btvolmais.setEnabled(false);
                btvolmenos.setEnabled(false);
                btcanalmais.setEnabled(false);
                btcanalmenos.setEnabled(false);
                btzoom.setEnabled(false);
                btmenu.setEnabled(false);
                btmute.setEnabled(false);
                btcc.setEnabled(false);
            
            }
            
           if (controleobj.mute == 1 || controleobj.volume == 0){
               LBmute.setVisible(true);
               LBvolume.setVisible (false);
           } else {
               LBvolume.setVisible(true);
               LBmute.setVisible(false);
           }
            
            //NETFLIX 
            if (controleobj.netflix == true) {
                LBcanal.setVisible(false);
                LBnetflix.setVisible(true);
            } else {
                LBcanal.setVisible(true);
                LBnetflix.setVisible(false);
            }
            
            //MENU
            if (controleobj.menu == true) {
                LBconfig.setVisible(true);
                LBaudio.setVisible(true);
                LBnet.setVisible(true);
                LBmenu1.setVisible(true);
            } else {
                LBconfig.setVisible(false);
                LBaudio.setVisible(false);
                LBnet.setVisible(false);
                LBmenu1.setVisible(false);
            }
            
            //LEGENDAS
            if (controleobj.captions == 1){
                LBlegendas.setVisible(true);
            } else {
               LBlegendas.setVisible(false); 
            }
            
            //Zoom
            switch (controleobj.zoom){
                case 1:
                  LBzoom.setText("ZOOM X1");
                  break;
                case 2:
                  LBzoom.setText("ZOOM X2");
                  break;
                case 3:
                  LBzoom.setText("ZOOM X3");
                  break;
                case 4:
                  LBzoom.setText("ZOOM X4");
                  break;
                case 5:
                  LBzoom.setText("ZOOM X5");
                  break;
                default: LBzoom.setText(" ");
            }
        }  
        
        public void nome_canal(String valor){
        if(temporizador_canal.length() < 2){
            temporizador_canal = temporizador_canal + valor.toString();

            if(temporizador != null){
                temporizador.stop();
            }

            temporizador = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    controleobj.canais(temporizador_canal);
                    temporizador_canal = "";
                    atualiza();
                }
            });

            temporizador.setRepeats(false);
            temporizador.start();
        }
            
        
        

        
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB0;
    private javax.swing.JLabel LBaudio;
    private javax.swing.JLabel LBcanal;
    private javax.swing.JLabel LBconfig;
    private javax.swing.JLabel LBlegendas;
    private javax.swing.JLabel LBmenu;
    private javax.swing.JPanel LBmenu1;
    private javax.swing.JLabel LBmute;
    private javax.swing.JLabel LBnet;
    private javax.swing.JLabel LBnetflix;
    private javax.swing.JLabel LBvolume;
    private javax.swing.JLabel LBzero;
    private javax.swing.JLabel LBzoom;
    private javax.swing.JPanel Tv;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btcanalmais;
    private javax.swing.JButton btcanalmenos;
    private javax.swing.JButton btcc;
    private javax.swing.JButton btmenu;
    private javax.swing.JButton btmute;
    private javax.swing.JButton btnetflix;
    private javax.swing.JButton btpower;
    private javax.swing.JButton btvolmais;
    private javax.swing.JButton btvolmenos;
    private javax.swing.JButton btzoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton btnTrocaCacais;
    // End of variables declaration//GEN-END:variables
}
